### ISSUE TITLE
Make connections with Cert-issues possible

### ISSUE THREAD

**Issue by AyteeDE** [jellyfin/jellyfin-ios#370]
I currently have a jellyfin server running in my home-network. 
I can access it from outside with a reverse proxy (Port 443) and a valid SSL-Cert.
Now I mapped the external domain to the local jellyfin ip in my local DNS to keep the traffic in my local network when I am at home.

Works fine on the webapp, but the dedicated clients fail to login. 
This is propably because the certificate is not valid and the client instantly blocks it.
Would be great if the app just asks if you want to connect even though the certificate is invalid.

**Comment by joshuaboniface** [comment]
This sounds like some sort of misconfiguration. If the cert is valid on the Internet, it should be valid to how you access it in-network too, otherwise your NAT reflection/DNS remapping is incorrectly set up.

i.e. if "https://jellyfin.mydomain.com" is your Internet-enabled access URI with a valid cert, and you use DNS remapping or NAT reflection to make "jellyfin.mydomain.com" redirect to the host inside your network, then the cert would still be valid. If you're trying to access it at another name, like "jellyfin.local", then it would not be.

This is of course outside of the point of the issue, but in terms of a workaround, ensuring your remapping is correct would "solve" the issue.

**Comment by thornbill** [comment]
We don't have any plans to support invalid certificates in the official apps (and iirc it's not possible with the current tech stack of this app anyway).
