### ISSUE TITLE
Crash when changing the server address

### ISSUE THREAD

**Issue by ALharchi** [jellyfin/jellyfin-ios#39]
Hello,
I had the server running on aaa.example.com and everything was workign fine.
I recently changed the address to bbb.example and now the app is showing an error contaction the server. When I go to Settings to change the address, the app goes all blank and become unresponsive.
I guess it would be good to allow changing the server address without reinstalling the app.

**Comment by thornbill** [comment]
This is caused by trying to access a property of the server info when info is undefined. When connecting to a server fails no `info` object is returned [here](https://github.com/jellyfin/jellyfin-expo/blob/master/screens/SettingsScreen.js#L130). This causes an error when we try to access properties of the `info` object in the render function [here](https://github.com/jellyfin/jellyfin-expo/blob/master/screens/SettingsScreen.js#L57).
