### ISSUE TITLE
iOS: Music: no integration with iOS Control Center

### ISSUE THREAD

**Issue by avibrazil** [jellyfin/jellyfin-ios#391]
**Describe the feature**
Please make the player display its status and allow control in the Control Center.

Image shows what I currently see when playing music.
![IMG_275B6E2514AA-1](https://user-images.githubusercontent.com/3484242/189714294-05f97858-f90c-40d0-92a0-75a30e6b9a63.jpeg)

**Comment by mord0d** [comment]
I have the same issue, but can be temporarily fixed: unplug your AirPods (playback will be paused automatically) and plug it back and tap Play (~~playback will be resumed automatically,~~ Notifications area and Control Center will show the playback status).

The other issue is, even if playback status works, iOS can ~~shut down the app~~ suspend the playback (after 30 minutes or so) but in the app it's “playing”. Pause and then unpause *may* lead to “unsupported stream” or something (probably if network/uplink changed while it suspended). I think these issues are connected at least partially (FIXME: if not, I'll create another issue).

**Comment by anthonylavado** [comment]
This is an issue that keeps coming up because of the way the app is currently a webview inside a special container.

For music playback, I do recommend the very awesome [Finamp](https://github.com/jmshrv/finamp) which is also available on the App Store.

That said, we'll keep this open (or I'll link it to another issue if an earlier one exists).

**Comment by anthonylavado** [comment]
So, similar to #19.
