### ISSUE TITLE
Jellyfin is not working on iOS device.

### ISSUE THREAD

**Issue by joe-zhang3** [jellyfin/jellyfin-ios#400]
**Describe the bug**

First, please allow me to express my appreciation regarding your hard work.

I can use my iphone to browse the library, however, when I try to watch a movie, it keeps spinning and end up with a "disable" icon. 

![image](https://user-images.githubusercontent.com/18140903/198052106-f8dfefc8-7913-4789-a3ae-cdcb48c8d184.png)
![image](https://user-images.githubusercontent.com/18140903/198052148-52405e9e-5e90-44f2-8009-ec48856047b0.png)

I tried to turn on "Use Native Video Player", a more weird scenario happens, that I can "hear" it is playing, but no visual stuff show off. 

Anything I can do regarding this? BTW, the Jellyfin client of macOS works fine, and VLC on my iPhone works fine too. 

**System (please complete the following information):**
 - iOS Version: 16.1
 - Jellyfin Expo version: 43.0.0
 - Jellyfin Server version: 1.8.5-8

**Comment by Arthedian** [comment]
I have the samé Issue on ipados 16.1. I notice, that the issue is only on h265, with h264 it's working without a problem. The server is running on RPI4 4GB

**Comment by Arthedian** [comment]
Probably this is duplicate of this https://github.com/jellyfin/jellyfin-expo/issues/344

**Comment by thornbill** [comment]
Is transcoding disabled?

**Comment by Arthedian** [comment]
Where I can check this?
I was reading again through the second thread and I have these additional information:
1) I was trying Swiftfin too and inside Swiftfin it is working
2) Native player doesn't help.

**Comment by thornbill** [comment]
Admin Dashboard > Users > Your User > Media Playback

Swiftfin can play more media formats directly, so that doesn't mean a whole lot.

**Comment by Arthedian** [comment]
Both settings doesn't work. 

![607E7D7A-4FAB-48B1-B17F-9B56A496FE0C](https://user-images.githubusercontent.com/5776865/202861174-85da8634-619b-4e58-bda4-bd803d2dbcdd.png)
![8136B031-41E8-424F-AB9B-A6669DF95D11](https://user-images.githubusercontent.com/5776865/202861181-fdbce7d4-e5d1-44ef-afc0-50161d80035f.png)

**Comment by adamzvolanek** [comment]
Adding a data point but happy to compare settings. My JellyFin works/playback on my iPhone running 16.1.2, Jellyfin Server version 10.8.8, and iOS app 1.5.0 (5.5.0.0)


I noticed with the latest update using the beta native video player gives an error of trying to transcode. Else works so far.

**Comment by redvegas** [comment]
I am having this issue as well. How is this fixed?
Video does not playback on my iPhone. I am connecting from outside the house but running into the same issue where the video player just blacks out, keeps loading forever, or will freeze completely. I have gotten it to go 4s into the movie then it freezes and stops loading and doesn’t play anymore. 
This only happens on my iPhone tho. I just tried it with a work computer and everything is working fine.
Also tested on an android device and it doesn’t work,same issue as iOS.

**Comment by nothing2obvi** [comment]
I am running Jellyfin 10.8.9 via Docker.

I am having this issue as well on an iPad mini 4 // iOS 15.7.5 // Jellyfin 1.5.0. Similar to @Arthedian, the issue is only for videos with H265 and VP9 codec. I understand that Jellyfin iOS [cannot play](https://jellyfin.org/docs/general/clients/codec-support/) H265 in `.mkv` containers and that it cannot play VP9, but I have transcoding enabled so I am surprised this is an issue. Transcoding works when using my other iOS devices (described below).

Using the Beta "Native Video Player" doesn't work and causes this error:
```
The media cannot be used on this device. - The AVPlayerItem instance has failed with the error code -11848 and domain "AVFoundationErrorDomain".
```

I don't have this problem on my iPhone 11 // iOS 16.3.1 // Jellyfin 1.5.0, or on my iPad (5th gen.) // iOS 15.5 // Jellyfin 1.5.0.

I will point out that on Swiftfin 1.0.1 on the iPad mini 4, no videos play at all. However, on my iPhone 11 and iPad (5th gen.), Swiftfin 1.0.1 works great. 

Perhaps this is just a limitation of an older iPad?

**Comment by nothing2obvi** [comment]
After updating to Jellyfin 10.8.10, I don't seem to have this problem anymore :)
